---
- hosts: linux
  vars:
    training:
      topic: ansible
      trainer: sathish
      mode: online
      lab: aws
  tasks:
  - name: print dictionary values
    debug:
      msg: "key is {{ item.key }} and value is {{ item.value }}"
    with_dict:
      - "{{ training }}"
